// --- TRANSLATIONS --- //
export const translations = {
    en: {
        loginWelcome: "Welcome to LabPortal", loginSubtitle: "Select your role and sign in.", facilityPortal: "Facility Portal", labOperations: "Lab Operations", gmDashboard: "GM Dashboard", systemAdmin: "System Admin", signIn: "Sign In", facilityDashboard: "Facility Dashboard", pendingOrders: "Pending Orders", resultsReady: "Results Ready", actionsRequired: "Actions Required", newJobOrder: "New Job Order", recentOrders: "Recent Orders", orderId: "Order ID", patient: "Patient", date: "Date", status: "Status", actions: "Actions", viewDetails: "View Details", search: "Search...", all: "All", submitted: "Submitted", inProgress: "In Progress", completed: "Completed", exception: "Exception", testResults: "Test Results", downloadPdf: "Download PDF", acknowledge: "Acknowledge Critical Results", labDashboard: "Lab Operations Dashboard", newOrders: "New Orders", samplesToAccession: "Samples to Accession", rejectedSamples: "Rejected Samples", resultsToVerify: "Results to Verify", avgTat: "Average TAT", activeJobs: "Active Jobs", facility: "Facility", manage: "Manage", gmDashboardTitle: "General Manager Dashboard", totalRevenue: "Total Revenue (Q3)", rejectionRate: "Rejection Rate", revenueTrends: "Revenue Trends", orderVolumeProvider: "Order Volume by Provider", reports: "Reports", adminPanel: "System Administrator Panel", userManagement: "User Management", testCatalog: "Test Catalog", providersPricing: "Providers & Pricing", systemHealth: "System Health", integrations: "Integrations", logout: "Logout", aiAssistant: "AI Assistant", notifications: "Notifications", lang: "العربية", addNewTest: "Add New Test", manageOrder: "Manage Order",
        explainResultsAI: "✨ Explain Results with AI", generatingExplanation: "Generating explanation...", aiExplanation: "AI Explanation", medicalDisclaimer: "Disclaimer: This is for informational purposes only and is not medical advice. Consult a healthcare professional.", askAnything: "Ask about lab operations, revenue...", suggestedQueries: "Suggested Queries", queryCriticalResults: "List orders with critical results", queryTodaysRevenue: "What's today's revenue?", queryPendingOrders: "How many orders are pending?",
    },
    ar: {
        loginWelcome: "مرحباً بكم في بوابة المختبر", loginSubtitle: "اختر دورك وقم بتسجيل الدخول.", facilityPortal: "بوابة المنشأة", labOperations: "عمليات المختبر", gmDashboard: "لوحة تحكم المدير العام", systemAdmin: "إدارة النظام", signIn: "تسجيل الدخول", facilityDashboard: "لوحة تحكم المنشأة", pendingOrders: "الطلبات المعلقة", resultsReady: "نتائج جاهزة", actionsRequired: "إجراءات مطلوبة", newJobOrder: "طلب عمل جديد", recentOrders: "الطلبات الأخيرة", orderId: "رقم الطلب", patient: "المريض", date: "التاريخ", status: "الحالة", actions: "الإجراءات", viewDetails: "عرض التفاصيل", search: "بحث...", all: "الكل", submitted: "مُرسل", inProgress: "قيد التنفيذ", completed: "مكتمل", exception: "استثناء", testResults: "نتائج التحاليل", downloadPdf: "تحميل PDF", acknowledge: "الإقرار بالنتائج الحرجة", labDashboard: "لوحة تحكم عمليات المختبر", newOrders: "طلبات جديدة", samplesToAccession: "عينات للاستلام", rejectedSamples: "عينات مرفوضة", resultsToVerify: "نتائج للمصادقة", avgTat: "متوسط زمن الإنجاز", activeJobs: "المهام النشطة", facility: "المنشأة", manage: "إدارة", gmDashboardTitle: "لوحة تحكم المدير العام", totalRevenue: "إجمالي الإيرادات (الربع الثالث)", rejectionRate: "معدل الرفض", revenueTrends: "اتجاهات الإيرادات", orderVolumeProvider: "حجم الطلبات حسب المنشأة", reports: "تقارير", adminPanel: "لوحة تحكم النظام", userManagement: "إدارة المستخدمين", testCatalog: "قائمة التحاليل", providersPricing: "المنشآت والتسعير", systemHealth: "حالة النظام", integrations: "التكاملات", logout: "تسجيل الخروج", aiAssistant: "المساعد الذكي", notifications: "الإشعارات", lang: "English", addNewTest: "إضافة تحليل جديد", manageOrder: "إدارة الطلب",
        explainResultsAI: "✨ شرح النتائج بالذكاء الاصطناعي", generatingExplanation: "جاري إنشاء الشرح...", aiExplanation: "شرح الذكاء الاصطناعي", medicalDisclaimer: "إخلاء مسؤولية: هذه المعلومات للأغراض الإعلامية فقط وليست نصيحة طبية. استشر أخصائي رعاية صحية.", askAnything: "اسأل عن عمليات المختبر، الإيرادات...", suggestedQueries: "الاستفسارات المقترحة", queryCriticalResults: "عرض الطلبات ذات النتائج الحرجة", queryTodaysRevenue: "ما هي إيرادات اليوم؟", queryPendingOrders: "كم عدد الطلبات المعلقة؟",
    }
};
export const useTranslation = (lang) => (key) => translations[lang][key] || key;
