export const USERS = {
    facility: { name: 'Dr. Ahmad Saleh', role: 'Facility User', initials: 'AS' },
    lab: { name: 'Layla Karim', role: 'Lab Business User', initials: 'LK' },
    gm: { name: 'Omar Abdullah', role: 'Lab GM', initials: 'OA' },
    admin: { name: 'Admin User', role: 'System Admin', initials: 'AU' },
};

export const initialOrders = [
    { id: 'ORD-2025-00125', patient: 'Abdullah Al-Fahad', nationalId: '1098765432', tests: ['CBC', 'Lipid Panel'], status: 'Results Ready', date: '2025-09-18', amount: 350.00, results: [{ name: 'Hemoglobin', value: '14.5 g/dL', range: '13.5-17.5', isCritical: false }, { name: 'Cholesterol', value: '210 mg/dL', range: '125-200', isCritical: true }], needsAcknowledgement: true, paymentStatus: 'Paid', collectionType: 'Home Visit', patientLocation: '1234 Al Urubah Rd, Riyadh' },
    { id: 'ORD-2025-00124', patient: 'Fatima Al-Zahrani', nationalId: '2087654321', tests: ['TSH'], status: 'In Progress', date: '2025-09-18', amount: 120.00, paymentStatus: 'Paid', collectionType: 'At Lab' },
    { id: 'ORD-2025-00123', patient: 'Khalid Al-Ghamdi', nationalId: '1076543210', tests: ['Glucose', 'HbA1c'], status: 'Submitted', date: '2025-09-17', amount: 180.00, paymentStatus: 'Unpaid', collectionType: 'At Lab' },
    { id: 'ORD-2025-00122', patient: 'Noura Al-Mutairi', nationalId: '2065432109', tests: ['Vitamin D'], status: 'Completed', date: '2025-09-16', amount: 250.00, results: [{ name: 'Vitamin D, 25-Hydroxy', value: '22 ng/mL', range: '30-100', isCritical: true }], needsAcknowledgement: false, paymentStatus: 'Paid', collectionType: 'Home Visit', patientLocation: '5678 King Fahd Rd, Riyadh' },
    { id: 'ORD-2025-00121', patient: 'Mohammed Al-Qahtani', nationalId: '1054321098', tests: ['CBC'], status: 'Exception', note: 'Reagent unavailable for one test.', date: '2025-09-15', amount: 75.00, needsAcknowledgement: true, paymentStatus: 'Paid', collectionType: 'At Lab' },
];

export const initialPatients = [ { name: 'Abdullah Al-Fahad', nationalId: '1098765432', dob: '1985-03-15', contact: '0501234567' }, { name: 'Fatima Al-Zahrani', nationalId: '2087654321', dob: '1992-07-22', contact: '0559876543' }];
export const initialTestCatalog = [
    { id: 'T01', name: 'Complete Blood Count (CBC)', code: 'CBC', price: 75.00, specimen: 'Whole Blood', tat: '4 hours' }, { id: 'T02', name: 'Lipid Panel', code: 'LIPID', price: 275.00, specimen: 'Serum', tat: '6 hours' }, { id: 'T03', name: 'Thyroid-Stimulating Hormone (TSH)', code: 'TSH', price: 120.00, specimen: 'Serum', tat: '8 hours' }, { id: 'T04', name: 'Fasting Glucose', code: 'GLUCOSE', price: 80.00, specimen: 'Plasma', tat: '2 hours' }, { id: 'T05', name: 'Hemoglobin A1c (HbA1c)', code: 'HBA1C', price: 100.00, specimen: 'Whole Blood', tat: '6 hours' }, { id: 'T06', name: 'Vitamin D, 25-Hydroxy', code: 'VITD', price: 250.00, specimen: 'Serum', tat: '24 hours' }, { id: 'T07', name: 'Comprehensive Metabolic Panel (CMP)', code: 'CMP', price: 450.00, specimen: 'Serum', tat: '8 hours' }, { id: 'T08', name: 'Urine Analysis', code: 'UA', price: 90.00, specimen: 'Urine', tat: '4 hours' }, { id: 'T09', name: 'Coagulation Panel (PT/INR)', code: 'COAG', price: 150.00, specimen: 'Plasma', tat: '6 hours' }, { id: 'T10', name: 'C-Reactive Protein (CRP)', code: 'CRP', price: 110.00, specimen: 'Serum', tat: '4 hours' }
];
export const initialProviders = [ { id: 'P01', name: 'Riyadh General Hospital', agreement: '10% Discount' }, { id: 'P02', name: 'Future Medical Center', agreement: 'Standard Price List' }, { id: 'P03', name: 'Hope Clinic', agreement: '15% Discount' }];
export const initialLabOrders = [ { ...initialOrders[2], status: 'New Order', facility: 'Riyadh General Hospital' }, { ...initialOrders[1], status: 'Sample to Accession', facility: 'Future Medical Center' }, { id: 'ORD-2025-00118', patient: 'Hassan Al-Shehri', tests: ['Coagulation Panel'], status: 'Rejected Sample', reason: 'Insufficient Quantity', facility: 'Riyadh General Hospital' }, { ...initialOrders[0], status: 'Result to Verify', facility: 'Future Medical Center' }, { id: 'ORD-2025-00117', patient: 'Sara Al-Jasser', tests: ['CBC'], status: 'Rejected Sample', reason: 'Hemolyzed', facility: 'Hope Clinic' }];
export const auditLogs = [ { timestamp: '2025-09-18 14:01:22', user: 'admin@lab.com', action: 'Logged In' }, { timestamp: '2025-09-18 13:55:04', user: 'layla.k@lab.com', action: 'Released results for ORD-2025-00119' }, { timestamp: '2025-09-18 12:10:45', user: 'ahmad.s@facility.com', action: 'Submitted new order ORD-2025-00125' }];
export const initialUsers = [
    { id: 'U01', name: 'Dr. Ahmad Saleh', email: 'ahmad.s@facility.com', role: 'Facility User', facility: 'Riyadh General Hospital', status: 'Active' }, { id: 'U02', name: 'Layla Karim', email: 'layla.k@lab.com', role: 'Lab Business User', facility: 'Main Lab', status: 'Active' }, { id: 'U03', name: 'Omar Abdullah', email: 'omar.a@lab.com', role: 'Lab GM', facility: 'Main Lab', status: 'Active' }, { id: 'U04', name: 'Fahd Al-Mutairi', email: 'fahd.m@facility.com', role: 'Facility User', facility: 'Future Medical Center', status: 'Inactive' }, { id: 'U05', name: 'Admin User', email: 'admin@lab.com', role: 'System Admin', facility: 'System', status: 'Active' }
];
